version: "3"
services:
  aouth_api:
    container_name: aouth_api
    depends_on:
      aouth_db:
        condition: service_healthy
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
  aouth_db:
    container_name: aouth_database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 33306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    devices:
      - "/dev/urandom:/dev/random"
volumes:
  mysql_data:
