services:
  oauth_api:
    container_name: oauth_api
    depends_on:
      oauth_db:
        condition: service_healthy
    build: .
    volumes:
      - .:/code
    ports:
      - 8080:8080

  oauth_db:
    container_name: oauth_database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 33306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 10s
      retries: 10
    devices:
      - "/dev/urandom:/dev/random"
volumes:
  mysql_data:
